# Generated by Django 4.1 on 2023-07-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='summary',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
