# Generated by Django 4.1 on 2023-07-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_media_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
    ]
